CREATE TABLE IF NOT EXISTS public.otp_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  token TEXT NOT NULL,
  type TEXT NOT NULL,
  user_data JSONB,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.otp_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access" ON public.otp_tokens
  FOR SELECT USING (true);

CREATE POLICY "Allow insert for anyone" ON public.otp_tokens
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow update for anyone" ON public.otp_tokens
  FOR UPDATE USING (true);

CREATE POLICY "Allow delete for anyone" ON public.otp_tokens
  FOR DELETE USING (true);
